version: "2.1"
services:
  server:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8111:8111"
    volumes:
      - ./teamcity-server/data:C:/ProgramData/JetBrains/TeamCity/data
      - ./teamcity-server/logs:C:/ProgramData/JetBrains/TeamCity/logs
    mem_limit: 2g
  agent:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
    environment:
      - SERVER_URL=http://server:8111
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
